### ISSUE TITLE
Please update instructions for conda install, numpy=1.18.3 is deprecated

### ISSUE THREAD

**Issue by thierrygrange** [GuntherLab/READv2#1]
Dear Thorsten
The instructions for conda install are not valid anymore, numpy=1.18.3 is deprecated and cannot be installed. Installing 1.18.4 leads to conflict with the other versions, including matplotlib. Not specifying any version works, except for the pip install of plinkio. Currently, a full conda install of read2 fails as indicated in here.

Hopefully, you could figure out one set of library versions that is fully compatible in between them and currently available resources on anaconda.

Best

Thierry

**Comment by thierrygrange** [comment]
It may be useful for you to have the error issue during the pip install step:
pip install plinkio
Collecting plinkio
  Using cached plinkio-0.9.8.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: plinkio
  Building wheel for plinkio (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-upkp6lzh/plinkio_37f71a9c0cec497da726247582180cbf/setup.py", line 101, in <module>
          entry_points={},
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/distutils/core.py", line 134, in setup
          ok = dist.parse_command_line()
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/distutils/dist.py", line 483, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/setuptools/dist.py", line 1048, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/distutils/dist.py", line 539, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/setuptools/dist.py", line 893, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in load
          return self.resolve()
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2471, in resolve
          module = __import__(self.module_name, fromlist=['__name__'], level=0)
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 28, in <module>
          from .metadata import pkginfo_to_metadata
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/wheel/metadata.py", line 16, in <module>
          from .vendored.packaging.requirements import Requirement
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/wheel/vendored/packaging/requirements.py", line 7, in <module>
          from ._parser import parse_requirement as _parse_requirement
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/wheel/vendored/packaging/_parser.py", line 10, in <module>
          from ._tokenizer import DEFAULT_RULES, Tokenizer
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/wheel/vendored/packaging/_tokenizer.py", line 6, in <module>
          from .specifiers import Specifier
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/wheel/vendored/packaging/specifiers.py", line 16, in <module>
          from .utils import canonicalize_version
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/wheel/vendored/packaging/utils.py", line 8, in <module>
          from .tags import Tag, parse_tag
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/wheel/vendored/packaging/tags.py", line 26, in <module>
          from . import _manylinux, _musllinux
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/site-packages/wheel/vendored/packaging/_manylinux.py", line 171, in <module>
          def _get_glibc_version() -> Tuple[int, int]:
        File "/home/paleogenomique/.conda/envs/readv2/lib/python3.7/functools.py", line 490, in lru_cache
          raise TypeError('Expected maxsize to be an integer or None')
      TypeError: Expected maxsize to be an integer or None
      [end of output]

The packages that were installed by conda when not specifying any library versions:
  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2024.2.2-hbcca054_0
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  freetype           conda-forge/linux-64::freetype-2.12.1-h267a509_2
  icu                conda-forge/linux-64::icu-67.1-he1b5a44_0
  kiwisolver         pkgs/main/linux-64::kiwisolver-1.4.4-py37h6a678d5_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.40-h41732ed_0
  libblas            conda-forge/linux-64::libblas-3.9.0-21_linux64_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-21_linux64_openblas
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-13.2.0-h807b86a_5
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-13.2.0-h69a702a_5
  libgfortran5       conda-forge/linux-64::libgfortran5-13.2.0-ha4646dd_5
  libgomp            conda-forge/linux-64::libgomp-13.2.0-h807b86a_5
  liblapack          conda-forge/linux-64::liblapack-3.9.0-21_linux64_openblas
  libnsl             conda-forge/linux-64::libnsl-2.0.1-hd590300_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.26-pthreads_h413a1c8_0
  libpng             conda-forge/linux-64::libpng-1.6.43-h2797004_0
  libsqlite          conda-forge/linux-64::libsqlite-3.45.2-h2797004_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-13.2.0-h7e041cc_5
  libzlib            conda-forge/linux-64::libzlib-1.2.13-hd590300_5
  matplotlib         conda-forge/linux-64::matplotlib-3.2.2-1
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.2.2-py37h1d35a4c_1
  ncurses            conda-forge/linux-64::ncurses-6.4.20240210-h59595ed_0
  numpy              conda-forge/linux-64::numpy-1.21.6-py37h976b520_0
  openssl            conda-forge/linux-64::openssl-3.2.1-hd590300_1
  pandas             conda-forge/linux-64::pandas-1.3.5-py37he8f5f7f_0
  pip                conda-forge/noarch::pip-24.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.1.2-pyhd8ed1ab_0
  python             conda-forge/linux-64::python-3.7.12-hf930737_100_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.9.0-pyhd8ed1ab_0
  python_abi         conda-forge/linux-64::python_abi-3.7-4_cp37m
  pytz               conda-forge/noarch::pytz-2024.1-pyhd8ed1ab_0
  readline           conda-forge/linux-64::readline-8.2-h8228510_1
  setuptools         conda-forge/linux-64::setuptools-59.8.0-py37h89c1867_1
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  sqlite             conda-forge/linux-64::sqlite-3.45.2-h2c6b66d_0
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_h4845f30_101
  tornado            conda-forge/linux-64::tornado-6.2-py37h540881e_0
  typing_extensions  conda-forge/noarch::typing_extensions-4.5.0-pyha770c72_0
  wheel              conda-forge/noarch::wheel-0.43.0-pyhd8ed1ab_0
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0

**Comment by thierrygrange** [comment]
Specifying no version at all of anything, including python, just the latest of python3 worked and the plinkio could be installed by pip conda create -n readv2 python=3 pandas numpy pip matplotlib The problem occurs when specifying python=3.7

**Comment by SonofLastPanda** [comment]
I received similar errors from the others as well, I am updating the README file. Thank you very much for bringing this to our attention.

**Comment by thierrygrange** [comment]
Thanks

Best

Thierry
