### ISSUE TITLE
ValueError a few seconds after run starts on example

### ISSUE THREAD

**Issue by batelz** [GuntherLab/READv2#3]
Hi,
When running the example you provided:
`python READ2.py -i Srubnaya.subset_bed`

I get an error:
 ```
   ===Thank you for using Relationship Estimation from Ancient DNA version 2 (R                                                                                                              EADv2)===

Window size: 5000000
Calculating one genome-wide P0 value and using a block-jackknife to estimate the standard error.
Traceback (most recent call last):
  File "READ2.py", line 366, in <module>
    s=6, rot=90, figsize=((8+0.1*(len(df_P0.index)), 8)), fontsize=8)
  File "/usr/lib/python3/dist-packages/pandas/plotting/_core.py", line 2941, in __call__
    sort_columns=sort_columns, **kwds)
  File "/usr/lib/python3/dist-packages/pandas/plotting/_core.py", line 1977, in plot_frame
    **kwds)
  File "/usr/lib/python3/dist-packages/pandas/plotting/_core.py", line 1743, in _plot
    kind=kind, **kwds)
  File "/usr/lib/python3/dist-packages/pandas/plotting/_core.py", line 845, in __init__
    super(ScatterPlot, self).__init__(data, x, y, s=s, **kwargs)
  File "/usr/lib/python3/dist-packages/pandas/plotting/_core.py", line 820, in __init__
    raise ValueError(self._kind + ' requires x column to be numeric')
ValueError: scatter requires x column to be numeric
```
What could be the issue?

Thank you,

**Comment by SonofLastPanda** [comment]
Hi @batelz,

Thank you for reporting the issue. Could you check: 

- the versions of the uploaded libraries in conda

- which version of READ you have clonned from Github

So I can try to replicate the issue myself.

**Comment by batelz** [comment]
Hi, and thank you for the fast reply @SonofLastPanda 

I was not using conda for the libraries, but pip:

```
(READ_V2) :~$ pip show pandas numpy pip matplotlib plinkio
Name: pandas
Version: 1.3.5
---
Name: numpy
Version: 1.21.6
---
Name: pip
Version: 24.0
---
Name: matplotlib
Version: 3.5.3
---
Name: plinkio
Version: 0.9.8
```

I've cloned the READv2 yesterday, so it's the most up to date version, I guess...

**Comment by SonofLastPanda** [comment]
Thank you for the extra information  @batelz!

Interestingly, I could run the script with those versions as well. I guess that there is something going on with the dependencies. I would suggest setting up the conda environment so the dependencies are managed better.
